# NOTE: Change headshots, 
#       follow up on inclusion of project managers, and
#       Update LinkedIn links


url: https://uncpmclub.com
baseurl: 



# Site settings
title: UNC Product Management Club
email: your-email@domain.com
description: "UNC Product Management Club partners with local tech startups and develops features for their products over the course of the semester. We provide
undergaraduate students interested in computer science, entreprenurship, business, UX, etc with hands on experience developing valuable products. We provide 
tech startups with fresh ideas on their products."


# Team names, titles and social links
people:
#- name: Yujie Tao
#  pic: 1
#  position: Founder
#  social:
#    - title: linkedin
#      url: https://www.linkedin.com/in/yujie-tao/

- name: Noah Davis
  pic: 17
  position: President
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/noahidavis/

- name: Rohan Venkatraman
  pic: 16
  position: VP of External Relations 
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/rohan-venkatraman/

# - name: Maddie Ewell
#   pic: 7
#   position: VP of Marketing 
#   social:
#     - title: linkedin
#       url: https://www.linkedin.com/in/maddieewell/
      
- name: Ryan Richardson
  pic: 20
  position: VP of Events 
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/ryan-s-richardson/

- name: Bernie Chen
  pic: 19
  position: VP of Marketing
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/berniechen/

#- name: Angie Shen
#  pic: 5
#  position: Graphic Design
#  social:
#    - title: linkedin
#      url: https://www.linkedin.com/in/mingxuan-shen-abb49b171/

- name: Cade Viney
  pic: 18
  position: Director of Product Management Lab 
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/cade-viney/
 
# - name: Jack Dewey
#   pic: 11
#   position: External Relations Committee Member 
#   social:
#     - title: linkedin
#       url: https://www.linkedin.com/in/jrdewey 
      
# - name: Jordan Cabrol
#   pic: 12
#   position: Project Manager 
#   social:
#     - title: linkedin
#       url: https://www.linkedin.com/in/jordan-cabrol-4218a2146/
      
# - name: Ayana Monroe
#   pic: 9
#   position: VP of Marketing 
#   social:
#     - title: linkedin
#       url: https://www.linkedin.com/in/ayana-monroe-958a47172/
      
# - name: Caroline Felman
#   pic: 14
#   position: Project Manager 
#   social:
#     - title: linkedin
#       url: https://www.linkedin.com/in/caroline-felman/
      
# - name: Kodjoga Bello
#   pic: 15
#   position: Project Manager 
#   social:
#     - title: linkedin
#       url: https://www.linkedin.com/in/kodjoga-bello-77h/
      
# - name: Julianna Surkin
#   pic: 16
#   position: Project Manager 
#   social:
#     - title: linkedin
#       url: https://www.linkedin.com/in/julianna-surkin/
      
# - name: Mira Rajesh
#   pic: 17
#   position: Project Manager 
#   social:
#     - title: linkedin
#       url: https://www.linkedin.com/in/mira-rajesh/

# - name: Jojo Yang
#   pic: 6
#   position: Graphic Designer
#   social:
#     - title: linkedin
#       url: https://www.linkedin.com/in/jojo-yang-11573a162/


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/UNC_PMClub/
  - title: linkedin
    url: https://www.linkedin.com/company/unc-product-management-club/
  - title: facebook
    url: https://www.facebook.com/UNCProductManagementClub/
  - title: github
    url: https://github.com/unc-pmclub


# Postal address (add as many lines as necessary)

# Build settings
markdown: kramdown
permalink: pretty
