# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll site to Pages

on:
  # Runs on pushes targeting the V2 branch
  push:
    branches: ["V2"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      # The URL will be the custom domain you have configured with GitHub Pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      VITE_WILLOW_TREE_PANEL: ${{ secrets.WILLOW_TREE_PANEL }}
      VITE_ATLASSIAN_APM_GUIDE: ${{ secrets.ATLASSIAN_APM_GUIDE }}
      VITE_MONGO_DB_SUMMER23_INTERN_GUIDE: ${{ secrets.MONGO_DB_SUMMER23_INTERN_GUIDE }}
      VITE_GOOGLE_PM_INTERVIEW_GUIDE: ${{ secrets.GOOGLE_PM_INTERVIEW_GUIDE }}
      VITE_GUMMADI_PM_RECRUITING_GUIDE: ${{ secrets.GUMMADI_PM_RECRUITING_GUIDE }}
      VITE_PMCLUB_WORKING_WITH_FIGMA: ${{ secrets.PMCLUB_WORKING_WITH_FIGMA }}
      VITE_PMCLUB_BEING_PROJECT_MANAGER: ${{ secrets.PMCLUB_BEING_PROJECT_MANAGER }}
      VITE_PMCLUB_JIRA_CONFLUENCE_TUTORIAL: ${{ secrets.PMCLUB_JIRA_CONFLUENCE_TUTORIAL}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Create CNAME file
        run: echo "www.uncpmclub.com" > ./dist/CNAME
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
